version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7-buster
    steps:
      - checkout
      # Restore Bundle cache
      - restore_cache:
          keys:
            - meta-rpc_client-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: sudo apt update && sudo apt install -y libsodium23
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      # Store Bundle cache
      - save_cache:
          key: meta-rpc_client-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          command: bundle exec rspec --format documentation
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    environment:
      IMAGE_NAME: meta-rpc_client
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t ${IMAGE_NAME}:latest .
  release:
    docker:
      - image: circleci/buildpack-deps:buster
    environment:
      IMAGE_NAME: meta-rpc_client
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate to Docker registry
          command: |
            echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t "${DOCKER_USER}/${IMAGE_NAME}:latest" .
      - run:
          name: Push Docker image
          command: |
            GIT_COMMIT_ID=$(git rev-parse --short HEAD)
            GIT_TAGS=$(git tag -l --points-at HEAD)

            docker tag "${DOCKER_USER}/${IMAGE_NAME}:latest" "${DOCKER_USER}/${IMAGE_NAME}:${GIT_COMMIT_ID}"
            docker push "${DOCKER_USER}/${IMAGE_NAME}:latest"
            docker push "${DOCKER_USER}/${IMAGE_NAME}:${GIT_COMMIT_ID}"

            while IFS= read -r git_tag; do
              docker tag "${DOCKER_USER}/${IMAGE_NAME}:${GIT_COMMIT_ID}" "${DOCKER_USER}/${IMAGE_NAME}:${git_tag}"
              docker push "${DOCKER_USER}/${IMAGE_NAME}:${git_tag}"
            done \<<< "${GIT_TAGS}"

workflows:
  build_test_and_release:
    jobs:
      - test
      - build
      - release:
          requires:
            - test
            - build
